### ISSUE TITLE
SQL Option?

### ISSUE THREAD

**Issue by P4R4NORM4L** [TheWolfBadger/VehicleTrustSystem#1]
Where is version 2.0 ?

**Comment by JaredScar** [comment]
Sadly not coming 😢

**Comment by P4R4NORM4L** [comment]
> Sadly not coming 😢

Ah man ! would of been cool though does it slow down if you get a lot of trusted vehicles ?

**Comment by JaredScar** [comment]
Not really. It's pretty quick because it still includes caching if I recall correctly
